In [1]:
import pandas as pd
df = pd.read_csv('~/Downloads/owid-covid-data.csv')
df.head() #先頭５行を表形式で表示する

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-01-23,NaN,0.0,NaN,NaN,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,Afghanistan,2020-01-24,NaN,0.0,NaN,NaN,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,Afghanistan,2020-01-25,NaN,0.0,NaN,NaN,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,Afghanistan,2020-01-26,NaN,0.0,NaN,NaN,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,Afghanistan,2020-01-27,NaN,0.0,NaN,NaN,0.0,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498

In [6]:
import pandas as pd
df = pd.read_csv('~/Downloads/owid-covid-data.csv')
df.info() #細かい情報を表示する

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60480 entries, 0 to 60479
Data columns (total 50 columns):
iso_code                              60164 non-null object
continent                             59847 non-null object
location                              60480 non-null object
date                                  60480 non-null object
total_cases                           51741 non-null float64
new_cases                             60357 non-null float64
new_cases_smoothed                    59401 non-null float64
total_deaths                          43883 non-null float64
new_deaths                            60357 non-null float64
new_deaths_smoothed                   59401 non-null float64
total_cases_per_million               51440 non-null float64
new_cases_per_million                 60041 non-null float64
new_cases_smoothed_per_million        59090 non-null float64
total_deaths_per_million              43595 non-null float64
new_deaths_per_million                60041 non-null float64
new_deaths_smoothed_per_million       59090 non-null float64
reproduction_rate                     39997 non-null float64
icu_patients                          4694 non-null float64
icu_patients_per_million              4694 non-null float64
hosp_patients                         5679 non-null float64
hosp_patients_per_million             5679 non-null float64
weekly_icu_admissions                 457 non-null float64
weekly_icu_admissions_per_million     457 non-null float64
weekly_hosp_admissions                742 non-null float64
weekly_hosp_admissions_per_million    742 non-null float64
total_tests                           23983 non-null float64
new_tests                             23837 non-null float64
total_tests_per_thousand              23983 non-null float64
new_tests_per_thousand                23837 non-null float64
new_tests_smoothed                    26595 non-null float64
new_tests_smoothed_per_thousand       26595 non-null float64
positive_rate                         25129 non-null float64
tests_per_case                        24538 non-null float64
tests_units                           27586 non-null object
stringency_index                      52701 non-null float64
population                            60164 non-null float64
population_density                    58577 non-null float64
median_age                            57320 non-null float64
aged_65_older                         56365 non-null float64
aged_70_older                         57004 non-null float64
gdp_per_capita                        57313 non-null float64
extreme_poverty                       39230 non-null float64
cardiovasc_death_rate                 57882 non-null float64
diabetes_prevalence                   58577 non-null float64
female_smokers                        44919 non-null float64
male_smokers                          44287 non-null float64
handwashing_facilities                30062 non-null float64
hospital_beds_per_thousand            52819 non-null float64
life_expectancy                       59848 non-null float64
human_development_index               57628 non-null float64
dtypes: float64(45), object(5)
memory usage: 21.9+ MB

In [7]:
import pandas as pd
df = pd.read_csv('~/Downloads/owid-covid-data.csv')
df['iso_code']

0        AFG
1        AFG
2        AFG
3        AFG
4        AFG
5        AFG
6        AFG
7        AFG
8        AFG
9        AFG
10       AFG
11       AFG
12       AFG
13       AFG
14       AFG
15       AFG
16       AFG
17       AFG
18       AFG
19       AFG
20       AFG
21       AFG
22       AFG
23       AFG
24       AFG
25       AFG
26       AFG
27       AFG
28       AFG
29       AFG
        ...
60450    ZWE
60451    ZWE
60452    ZWE
60453    ZWE
60454    ZWE
60455    ZWE
60456    ZWE
60457    ZWE
60458    ZWE
60459    ZWE
60460    ZWE
60461    ZWE
60462    ZWE
60463    ZWE
60464    ZWE
60465    ZWE
60466    ZWE
60467    ZWE
60468    ZWE
60469    ZWE
60470    ZWE
60471    ZWE
60472    ZWE
60473    ZWE
60474    ZWE
60475    ZWE
60476    ZWE
60477    ZWE
60478    ZWE
60479    ZWE
Name: iso_code, Length: 60480, dtype: object

In [8]:
import pandas as pd
df = pd.read_csv('~/Downloads/owid-covid-data.csv')
df['iso_code']=='GBR'

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
60450    False
60451    False
60452    False
60453    False
60454    False
60455    False
60456    False
60457    False
60458    False
60459    False
60460    False
60461    False
60462    False
60463    False
60464    False
60465    False
60466    False
60467    False
60468    False
60469    False
60470    False
60471    False
60472    False
60473    False
60474    False
60475    False
60476    False
60477    False
60478    False
60479    False
Name: iso_code, Length: 60480, dtype: bool